// export const backendURL = "http://192.168.43.165:4000"; //RAFAY
// export const backendURL = "http://192.168.159.165:4000"; //RAFAY2
// export const backendURL = "http://192.168.8.100:4000"; //PUCIT
//export const backendURL = "http://localhost:4000";
export const imgBBApiKey=process.env.REACT_APP_IMG_BB_API_KEY;
export const backendURL=process.env.REACT_APP_API_URL;
export const imgBBURL = "https://api.imgbb.com/1/upload";
export const api2PdfURL="https://v2018.api2pdf.com/chrome/html";
export const statesURL="https://countriesnow.space/api/v0.1/countries/states";
export const citiesURL="https://countriesnow.space/api/v0.1/countries/state/cities";
export const signUpURL = '/api/v0.1/usersignup'
export const modelURL = "/api/dog_model"
export const signInURL = '/api/v0.1/userLogin'
export const dogApiURL = '/api/v0.1/dogApi'
export const allBreedsURL = '/api/v0.1/breeds'
export const allDiseasesURL = '/api/v0.1/diseases'
export const getUserURL='/api/v0.1/user'
export const getFeaturedDogsURL="/api/v0.1/featureddogs"
export const getShelterURL="/api/v0.1/getshelterpage"
export const getShelterDogsURL="/api/v0.1/shelterdogs"
